apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Chart.Name }}
spec:
  schedule: "0 10 1/14 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:test" 
            #image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" 
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["python", "run.py"]
          restartPolicy: Never
